const { test, expect } = require('./support/test-base');
const {
    requireFixture,
    hasCareerData,
    hasTeamGameStats,
    hasPlayerFile,
    hasTeamTriviaData,
    hasGameTriviaData,
    hasPlayerTriviaData,
} = require('./support/probes');

// Generic, data-driven sorting checks.
//
// Instead of one hand-written test per sortable column, each entry below
// produces ONE test that walks every sortable column of that view's table and
// asserts a handful of invariants that hold regardless of what the column
// actually contains (numbers, dates, "12:28:05", "1-2-12", team names, ...):
//
//   1. clicking a sortable header shows exactly one caret, on that column
//   2. clicking it again flips the caret to the opposite direction
//   3. the set of displayed values is unchanged (no row lost, added or mutated)
//   4. the ascending value sequence is the exact reverse of the descending one
//   5. the order actually changes at all (unless every value is identical)
//
// Invariant 4 is the interesting one: a multiset has exactly one ascending and
// one descending ordering, so this holds even when many rows are tied - no
// parsing of the cell text is needed, and no fixture values are hard-coded.
// It assumes the displayed text is a function of the sort key. For a column
// where it isn't (cell shows a formatted value, sorting happens on a different
// underlying field), list its header in `looseColumns` to fall back to
// invariants 1-3 and 5 only.

const BASE = 'http://localhost:8000';

const VIEWS = [
    {
        name: 'Team stats',
        url: `${BASE}/index.html#!/team_stats/2025`,
        table: '#standings',
        probe: hasTeamGameStats('2025'),
    },
    {
        name: 'Team profile game log',
        url: `${BASE}/index.html#!/team_profile/2025/NIT`,
        table: '#basic_game_by_game',
        probe: hasTeamGameStats('2025'),
    },
    {
        name: 'Player profile game log',
        url: `${BASE}/index.html#!/player_profile/2025/NIT/4`,
        table: '#basic_game_by_game',
        probe: hasPlayerFile('2025', 'NIT', '4'),
    },
    {
        name: 'Team trivia',
        url: `${BASE}/index.html#!/team_trivia`,
        table: 'table',
        probe: hasTeamTriviaData,
    },
    {
        name: 'Game trivia',
        url: `${BASE}/index.html#!/game_trivia`,
        table: 'table',
        probe: hasGameTriviaData,
    },
    {
        name: 'Player trivia',
        url: `${BASE}/index.html#!/player_trivia`,
        table: 'table',
        probe: hasPlayerTriviaData,
    },
    // career_stats renders thousands of rows; sorting every column there is
    // slow, so it waits for its big data file and only samples a few columns.
    // It also shows just the first `ctrl.limit` (100) rows of the sorted list.
    {
        name: 'Career stats',
        url: `${BASE}/index.html#!/career_stats`,
        table: 'table',
        probe: hasCareerData,
        waitForData: /upd_full_career_stats_stripped\.json/,
        maxColumns: 5,
        windowed: true,
    },
];

// 'down' | 'up' | null - ng-show hides the inactive caret via display:none,
// so visibility is the reliable signal here
async function readCaret(th) {
    if (await th.locator('.fa-caret-down:visible').count()) return 'down';
    if (await th.locator('.fa-caret-up:visible').count()) return 'up';
    return null;
}

// Rows generated by ng-repeat. A tbody can also hold static rows - the "Gesamt:"
// summary row of the game logs - that stay at the bottom whichever way the
// table is sorted, so they must not be part of the ordering checks.
const DATA_ROWS = 'tbody > tr[data-ng-repeat], tbody > tr[ng-repeat]';

// text of one column, top to bottom, addressed positionally so it works for
// tables that mix <td> and <th> in the body
function columnValues(table, columnIndex) {
    return table
        .locator(DATA_ROWS)
        .evaluateAll(
            (trs, idx) => trs.map((tr) => (tr.children[idx]?.textContent || '').trim()),
            columnIndex,
        );
}

// A plain number ("52", "-3", "12,5 %"), or null for anything else (times,
// records, names, empty cells). Only columns made up entirely of plain numbers
// get the monotonic-order check below.
function plainNumber(text) {
    return /^[-+]?\d+(?:[.,]\d+)?\s*%?$/.test(text)
        ? parseFloat(text.replace(',', '.').replace('%', ''))
        : null;
}

// null when the column is not purely numeric or is in order, else a description
function orderViolation(values, direction) {
    const numbers = values.map(plainNumber);
    if (numbers.some((n) => n === null)) return null;
    for (let i = 1; i < numbers.length; i++) {
        const outOfOrder =
            direction === 'up' ? numbers[i] < numbers[i - 1] : numbers[i] > numbers[i - 1];
        if (outOfOrder) return `${numbers[i - 1]} is followed by ${numbers[i]}`;
    }
    return null;
}

for (const view of VIEWS) {
    test(`Sorting invariants: ${view.name}`, async ({ page }) => {
        await requireFixture(page, view.probe);

        if (view.waitForData) {
            const [response] = await Promise.all([
                page.waitForResponse((res) => view.waitForData.test(res.url()), {
                    timeout: 15000,
                }),
                page.goto(view.url),
            ]);
            expect(response.ok()).toBeTruthy();
        } else {
            await page.goto(view.url);
        }

        const table = page.locator(view.table).first();
        await expect(table).toBeVisible({ timeout: 15000 });

        const rows = table.locator(DATA_ROWS);
        await expect(rows.first()).toBeVisible({ timeout: 15000 });
        const initialRowCount = await rows.count();
        expect(initialRowCount).toBeGreaterThan(0);

        const headers = table.locator('thead th');
        const headerCount = await headers.count();
        expect(headerCount).toBeGreaterThan(0);

        // positional column addressing is only valid when the header row and
        // the body rows have the same cell count (no colspans in play)
        const bodyCellCount = await rows.first().locator('> *').count();
        const canReadColumns = bodyCellCount === headerCount;

        // a header is sortable exactly when the shared table_header directive
        // wrapped it in a link
        const sortable = [];
        for (let i = 0; i < headerCount; i++) {
            const th = headers.nth(i);
            if (await th.locator('a').count()) {
                sortable.push({ index: i, label: (await th.innerText()).trim() });
            }
        }
        expect(sortable.length, `${view.name}: no sortable columns found`).toBeGreaterThan(0);

        const columns = view.maxColumns ? sortable.slice(0, view.maxColumns) : sortable;

        for (const column of columns) {
            const th = headers.nth(column.index);
            const where = `${view.name} / column "${column.label}"`;

            // --- first click: establishes a sort direction on this column ---
            await th.locator('a').first().click();
            await expect
                .poll(() => readCaret(th), {
                    message: `${where}: no caret shown after sorting by this column`,
                    timeout: 5000,
                })
                .not.toBeNull();
            const firstCaret = await readCaret(th);

            // the caret is driven by the same sortConfig as the ng-repeat's
            // orderBy, so once it has rendered the rows are in their new order
            const carets = table.locator(
                'thead .fa-caret-down:visible, thead .fa-caret-up:visible',
            );
            expect(await carets.count(), `${where}: more than one caret visible`).toBe(1);

            const firstValues = canReadColumns
                ? await columnValues(table, column.index)
                : await rows.allTextContents();

            // --- second click: must toggle to the opposite direction ---
            await th.locator('a').first().click();
            const expectedCaret = firstCaret === 'down' ? 'up' : 'down';
            await expect
                .poll(() => readCaret(th), {
                    message: `${where}: caret did not toggle to ${expectedCaret}`,
                    timeout: 5000,
                })
                .toBe(expectedCaret);

            const secondValues = canReadColumns
                ? await columnValues(table, column.index)
                : await rows.allTextContents();

            // sorting must never filter, duplicate or alter rows
            expect(secondValues.length, `${where}: row count changed while sorting`).toBe(
                firstValues.length,
            );
            // a windowed view shows only the first N rows of a longer list, so
            // ascending and descending legitimately show different rows
            if (!view.windowed) {
                expect([...secondValues].sort(), `${where}: displayed values changed`).toEqual(
                    [...firstValues].sort(),
                );
            }

            const allEqual = new Set(firstValues).size <= 1;
            if (allEqual) continue;

            // the column reacts to being sorted at all - catches a header wired
            // to a sort key that does not exist on the data (the row order then
            // silently stays put)
            expect(secondValues, `${where}: sort direction had no effect on the order`).not.toEqual(
                firstValues,
            );

            if (!canReadColumns) continue;

            // orderBy reverses ties when the direction flips, so a header wired
            // to a key the data does not have still "changes the order" above.
            // For numeric columns the values themselves show whether the rows
            // are really sorted by them.
            const firstDirection = firstCaret;
            for (const [values, direction] of [
                [firstValues, firstDirection],
                [secondValues, expectedCaret],
            ]) {
                const violation = orderViolation(values, direction);
                expect(
                    violation,
                    `${where}: values are not sorted ${direction === 'up' ? 'ascending' : 'descending'} (${violation})`,
                ).toBeNull();
            }

            if (view.windowed) continue;
            if ((view.looseColumns || []).includes(column.label)) continue;

            // ascending and descending are the two orderings of one multiset,
            // so each must be the exact reverse of the other - true even with
            // ties, and without knowing how the values compare
            expect(
                secondValues,
                `${where}: ascending order is not the reverse of descending`,
            ).toEqual([...firstValues].reverse());
        }
    });
}
